### ISSUE TITLE
Windows: Disable exclusive fullscreen mode

### ISSUE THREAD

**Issue by kazatsuyu** [kvark/blade#103]
I was working on a fullscreen implementation at https://github.com/zed-industries/zed/pull/9728 and ran into a problem where it would automatically go into exclusive fullscreen mode, and it needed to use `VK_EXT_full_screen_exclusive` to fix this.

https://github.com/kazatsuyu/blade/commit/662787b62a046be1d650326d6a9eed2cd29281d8
This is my quick implementation and I have confirmed that it works, but I don't know much about `blade` internals and don't have a lot of knowledge of Vulkan, so I would need to consult with you on how to implement it.

**Comment by kazatsuyu** [comment]
Sorry, sent by mistake before writing details

**Comment by kvark** [comment]
Thank you for drafting this!
I was thinking that we'd add a field to the surface config:
```rust
struct SurfaceConfig {
...
  pub allow_exclusive_fullscreen: bool,
}
```
And then in Vulkan backend this flag would drive the use of `VK_EXT_full_screen_exclusive` extension, if present
