### ISSUE TITLE
"Memory block wasn't deallocated" is printed when exiting Zed builds on Linux

### ISSUE THREAD

**Issue by mikayla-maki** [kvark/blade#106]
A little sleuthing reveals that this error comes from the `gpu_alloc` crate, and is run when it's `MemoryBlock` type is dropped without calling `MemoryBlock::deallocate`. Probably because the `MemoryManager` in `blade-graphics/src/vulkan/mod.rs` isn't being cleared in this case.

**Comment by kvark** [comment]
Following the comment of #107 - unless this is reproducible on the examples, it's likely a problem on the application side
