### ISSUE TITLE
Is web supported?

### ISSUE THREAD

**Issue by amokfa** [kvark/blade#137]
In the talk delivered a year ago you showed a wasm demo, but I found this line in the docs:

https://github.com/kvark/blade/blame/6e2103583478366084be68456d82acf50dfb283d/blade-graphics/etc/FAQ.md#L5

Is it outdated? How well supported is web compared to native?

**Comment by kvark** [comment]
Ah, thanks for spotting! This line is outdated. Blade has had WebGL2 backend working for a while. See https://github.com/kvark/blade/tree/main/blade-graphics#webgl2
