### ISSUE TITLE
example "scene" "particle" not working?

### ISSUE THREAD

**Issue by kiinoo** [kvark/blade#157]
tried to run `cargo run --release --example scene`, got the following err:

```
thread 'main' panicked at blade-graphics/src/metal/pipeline.rs:150:63:
not implemented
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

also, run `cargo run --release --example particle`, nothing drawn

env: 
macOS Sonoma, with chip: Apple M1 Ultra

**Comment by kvark** [comment]
Thanks for the report!
The "scene" example isn't going to work on Metal since it uses all of the ray tracing capabilities, and the Metal backend only supports the very basics.
I wasn't aware that the particle example didn't work on Metal, it should work, and I'll fix it.
