### ISSUE TITLE
Support for multisampled textures + resolve?\

### ISSUE THREAD

**Issue by EriKWDev** [kvark/blade#198]
I see there are some indications in the code that `sample_count` was almost added to the texture descriptor but don't see it implemented yet.

What would be the challenges in supporting multisampled textures and resolve targets for render passes? I would be happy to help though I have mostly experience with wgpu:s user-facing code

(side note: Such a fresh breath of air to read this code! It's all so simple.. blade-graphics looks very promising and I would like to give blade a try for our rendering engine at my company that's currently using wgpu (for this game https://idno.se/swap/). Seeing your presentation and descirbing the simple binding model in blade really motivated me after having to deal with so much pipeline description and setup of bind groups for our multiple shader permutations... )

**Comment by kvark** [comment]
I haven't investigated this again since WebGPU times, but I think the support for MSAA will largely look the same as in wgpu. The sample count needs to be used and respected by the texture creation. Then we'll need extra data in `RenderPipelineDesc` to specify the resolve target. This is the only way with zero translation overhead to both Vulkan and Metal.

**Comment by EriKWDev** [comment]
I made some experiments in my fork and also dåfoun that there was a ClearOp::ResolveTo(TextureView) in the code which I successfully used together with some more info in the texture_descriptor for sample count and some more msaa state in the renderpipelinedesc to get msaa working for the particles demo. I did have some issues with it though on my intel integrted graphics laptop as well as an intel+nvidia machine, though my Ryzen+AMD gpu seemed to work fine. None of the targets had validarion errors.

I will investigate more and get back, though on vacation atm

**Comment by kvark** [comment]
Yes, I think this is a fine way to expose it in the API. Technically, one could try to both store the result and resolve it in Vulkan, but that isn't very useful. If we provide this through `ClearOp`, it becomes very neatly out of the way for most usages.

**Comment by kvark** [comment]
I'm finishing working on #203 and thinking about making a release. Would you want to prototype a change to squeeze into blade-graphics-0.6 about multisampling? @EriKWDev

**Comment by EriKWDev** [comment]
#203 looks like a nice addition! 

I am still on vacation and will be back in December so will not be able to contribute much work until then sadly.

So if a release is in order then go ahead! 


(On a side-note I also started investigating https://docs.vulkan.org/features/latest/features/proposals/VK_KHR_dynamic_rendering_local_read.html on the airplane as well as it might become relevant for our company in the future too, though support in drivers seemed not great at the moment)

**Comment by EriKWDev** [comment]
Getting back at this for my next flight home but I am struggling a lot with the opengl es implementation of the finishop resolve. The textures are only represented as either textures or renderbuffers but in order to resolve them using `gl.blit_framebuffer` we need FBO:s. Seems bad to create and remove framebuffers each time we need to resolve them.

Haven't done much msaa rendering in gles but wasn't entirely obvious how to resolve a multisampled texture there.

Vulkan and metal was easier, though I need to get to a computer at work in order to test that the metal implementation actually works

**Comment by kvark** [comment]
This is pretty much what wgpu-hal is also doing - https://github.com/gfx-rs/wgpu/blob/02b28e28f0f0904a943de44b647bf18a66ac4fc4/wgpu-hal/src/gles/queue.rs#L1107-L1133
It does reuse both the FBOs though instead of recreating them
