### ISSUE TITLE
Publish crate with new version (egui)

### ISSUE THREAD

**Issue by apekros** [kvark/blade#200]
Forgot to mention in #197 as I wasn't sure on your publish procedures, but would it be possible to get a pushed version to crates (reflective of the egui bump, and any recent changes), sorry about that!

**Comment by kvark** [comment]
Which crates do you actually need? The only crate that depends on `winit` is the top-level `blade` crate. Everything below it is winit-agnostic.

**Comment by apekros** [comment]
> Which crates do you actually need? The only crate that depends on `winit` is the top-level `blade` crate. Everything below it is winit-agnostic.

blade-egui due to the egui bump I think?

**Comment by kvark** [comment]
Ah, got it, ok, let me get that tonight

**Comment by kvark** [comment]
https://crates.io/crates/blade-egui/0.5.0 is up
let me know if anything else is needed!
