### ISSUE TITLE
egui more pixelated than normal?

### ISSUE THREAD

**Issue by EriKWDev** [kvark/blade#215]
I don't know if it is just me but it looks like egui in blade is more pixelated than I am used to and I don't know what the reason is.

Left is egui with wgpu in our game and right is blade

![image](https://github.com/user-attachments/assets/686b8c25-f6c2-438e-a61e-605251c2b902)

![image](https://github.com/user-attachments/assets/4abdc5b9-ce99-428f-83fd-e059e79d78c5)

Not perfectly scientific

**Comment by kvark** [comment]
The best way to answer this question is to capture these 2 scenarios in something like RenderDoc and share the captures.

One thing that is different is the sampler. Blade is using a single [Linear sampler](https://github.com/kvark/blade/blob/099555282605c7c4cca9e66a8f40148298347f80/blade-egui/src/lib.rs#L161-L167). Wgpu's implementation is more comprehensive and it has a map of different samplers chosen [based on the image](https://github.com/emilk/egui/blob/046034f9020453f1ffe3e96ff26c5404435fcfb5/crates/egui-wgpu/src/renderer.rs#L651-L654).

**Comment by EriKWDev** [comment]
captures, contains the render with current blade main branch, render with blade from #216 as well as render with eframe wgpu

[blade_egui_renderdoc_captures.zip](https://github.com/user-attachments/files/18049777/blade_egui_renderdoc_captures.zip)

**Comment by kvark** [comment]
Thank you for investigation! I left some notes on #216.
It would also help to get a wgpu API trace, so that I can replay this on different platform.

**Comment by EriKWDev** [comment]
> It would also help to get a wgpu API trace, so that I can replay this on different platform.

Trying to create one though egui-wgpu wasn't setup with that feature in mind so had to do some changes there upon wgpu device creation.

There seems to be a wpgu regression at the moment that has removed the trace functionality?
https://github.com/gfx-rs/wgpu/issues/5974

```console
[2024-12-08T09:37:35Z ERROR wgpu::backend::wgpu_core] Feature 'trace' has been removed temporarily, see https://github.com/gfx-rs/wgpu/issues/5974
```

Will see if I can get it to run with older version...

**Comment by EriKWDev** [comment]
I have run into a hoard of different issues with wgpu panicking on destroyed semaphores and egui-winit/egui-wgpu/winit/wgpu versions not being compatible..

Finally have a minimal reproducible that uses a version of wgpu that supports tracing as well as a version of the egui renderer that seems to produce a correct result like eframe.

Available here: https://github.com/ErikWDev/minimal_wgpu_egui

*wgpu trace*: [egui_wgpu_trace.zip](https://github.com/user-attachments/files/18051842/egui_wgpu_trace.zip)

*renderdoc capture of real application* [egui_winit_wgpu__renderdoc_1_35_capture.zip](https://github.com/user-attachments/files/18051830/egui_winit_wgpu__renderdoc_1_35_capture.zip)

Sadly, when I tried to replay the wgpu trace it just produced a black screen :/ Don't know how to proceed. Hopefully the minimal code at https://github.com/ErikWDev/minimal_wgpu_egui is good enough

**Comment by EriKWDev** [comment]
A new observation is that I got egui-wgpu to also render to a SRGB target but it still produces correct results:

![image](https://github.com/user-attachments/assets/fededcdb-ace0-4a28-be41-ad151a211cac)

**Comment by kvark** [comment]
Do you have the corresponding Blade example? or is the example in your PR does exactly this?
I took a RenderDoc capture locally from your [minimal_wgpu_egui](https://github.com/ErikWDev/minimal_wgpu_egui) and compared it to the capture of Blade (current) that you provided. The target and source formats all match, the samplers all match.
One thing is different though - the blend mode.
wgpu:
![snip-wgpu](https://github.com/user-attachments/assets/9ed158de-e3d8-4ea6-a6ab-e5e2bd23a78a)

blade:
![snip-blade](https://github.com/user-attachments/assets/345b51ee-9d36-4c25-a379-855b51e95b47)

So that should be easy to test

**Comment by kvark** [comment]
Ok, found https://github.com/emilk/egui/pull/2071
That explains our difference. It's a bit unfortunate though because any normal pipeline will want to output linear, and egui wants to output gamma. But we can work around it. I can do a small PR.

**Comment by kvark** [comment]
@EriKWDev it would be great to get your feedback on https://github.com/kvark/blade/pull/217 (ideally, a confirmation that it fixes your issue?) before we proceed.

**Comment by EriKWDev** [comment]
Well spotted with the blending function as well as finding the source in egui for the explanation on anti-aliasing in gamma not linear
