### ISSUE TITLE
Ability to describe render-pipelines without a fragment shader

### ISSUE THREAD

**Issue by EriKWDev** [kvark/blade#226]
The `RenderPipelineDesc` has a mandatory `pub fragment: ShaderFunction<'a>` field.

For a vertex-only shader it doesn't make sense to require the declaration of a fragment shader

I propose it change to a `pub fragment: Option<ShaderFunction<'a>>` instead

**Comment by kvark** [comment]
I double-checked this, and indeed both Vulkan and Metal will be happy, no workarounds needed to support that. We should do it.
