### ISSUE TITLE
Access to ordered timings data

### ISSUE THREAD

**Issue by EriKWDev** [kvark/blade#231]
I see that in all implementations there is a zip-iterator that associates names and timings, but they are subsequently inserted into a hashmap loosing the ordering.

What is the reasoning and would you accept a PR changing it to get out a `&[(String, Duration)]` and internally just store it as a `Vec` instead to not loose the ordering?

I guess this is just convenient syntax rather than an intentional summation of same names? I have several `blit` which now get summed. Could ofc change names

```rust
*self.timings.entry(pass_name).or_default() += time;
```

**Comment by kvark** [comment]
No strong opinion on this. In fact, the first implementation was doing exactly `&[(String, Duration)]`. However, when I started running with it, I realized that I have multi-pass stages, and seeing 5-20 entries of the same name is just not practical. That's where I figured that building a hashmap instead would make this nicer.

If one needs detailed timings, one should use the platform-specific tools. Like NVidia Nsight Graphics, or RenderDoc.
The built-in timings are there only for high-level overview.

**Comment by EriKWDev** [comment]
I use the Radeon GPU Profiler for all profiling, but it's nice to also have the built in overview, and getting them in the order of execution is the way I prefer reading them.

I see the use-case for merging the names, though since that can be done very easily on-top of the slice output I think still not having the API remove the order is better

**Comment by kvark** [comment]
> that can be done very easily on-top of the slice output

Indeed, I'll just do this conversion locally.
